---
title: "Publications"
---

Korutla, R.; Tedder, D.; Brogan, K.; Milosevic, M.; **Wilczek, M.P.**; Shehadeh, N.; Shara, N.; Ross, 
E.G.; Amal, S. Analysis and Visualization of Confounders and Treatment Pathways Leading to 
Amputation and Non-Amputation in Peripheral Artery Disease Patients Using Sankey Diagrams: 
Enhancing Explainability. Biomedicines 2025, 13, 258.  


Pike, A.M.C.; Amal, S.; Maginnis, M.S.; **Wilczek, M.P.** Evaluating Neural Network Performance in 
Predicting Disease Status and Tissue Source of JC Polyomavirus from Patient Isolates Based on 
the Hypervariable Region of the Viral Genome. Viruses 2025, 17, 12.  


Bond A.C.S., Crocker M.A., **Wilczek M.P.**, DuShane J.K., Sandberg A.L., Bennett L.J., Leclerc N.R., 
Maginnis M.S. High-throughput drug screen identifies calcium and calmodulin inhibitors that 
reduce JCPyV infection. Antiviral Res. 2024 Jan 19;222:105817. doi: 
10.1016/j.antiviral.2024.105817. Epub ahead of print. PMID: 38246207.


Wong C.N., **Wilczek M.P.**, Smith L.H., Bosse J.D., Richard E.L., Cavanaugh R., Manjourides J., 
Orkaby A.R., Olivieri-Mui B. Frailty Among Sexual and Gender Minority Older Adults: The All of 
Us Database. J Gerontol A Biol Sci Med Sci. 2023 Oct 28;78(11):2111-2118. doi: 
10.1093/gerona/glad149. PMID: 37485864; PMCID: PMC10613018. 